#ifndef CONSTANT_H
#define CONSTANT_H

#define SCREEN_WIDTH 350
#define SCREEN_HEIGHT 700

#define PLAYER_STEP 3

#define NUM_BACKGROUND 4

#define NUM_LEVEL 4

#define ACTIVATE_FROZEN_TIME 2.5

#define ACTIVATE_INVISIBLE_TIME 6.0

#define NUM_INVISIBLE 0

#define RED_LIGHT 1
#define GREEN_LIGHT 4

#define RED_LIGHT_2 0.7
#define GREEN_LIGHT_2 3

#define NUM_FROZEN 0
#endif